
format = '''
$os$time$git_branch$git_status
$directory $character
'''

scan_timeout = 10

add_newline = false

[username]
show_always = true
style_user = "#ff79c6"
style_root = "bg:#9A34E8"
format = '[$user]($style)'

[directory]
style = "#ffb86c"
format = "[ $path]($style)"
truncation_length = 5
truncation_symbol = "…/"

# 替换
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
".ssh" = ""
".config" = ""

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch](fg:#769ff0)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind)](fg:#769ff0)]($style)'

[os]
format = "[ ]($style)"
style = "#ffffff"
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "#8be9fd"
format = '[$time]($style)'

[status]
format = '$symbol'
symbol = '[❯](red)'
success_symbol = '[❯](#50fa7b)'
map_symbol = true
disabled = false
not_found_symbol = '[](#f1fa8c)'
not_executable_symbol = ''

[fill]
symbol = ' '

[nodejs]
format = '[ $version](#bd93f9) '
disabled = true

[rust]
format = '[ $version](#bd93f9)'
disabled = true

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[conda]
format = '[$environment](#bd93f9) '
disabled = true

[cmd_duration]
min_time = 50
format = '[$duration](#f1fa8c)'

